### ISSUE TITLE
Help with updating ruby, node, gems, npm

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#58]
I'm got a full refresh to all dependencies here: #56.

However, I can't get `rspec` to run:

```
Add new comment
  add post via horizontal, stacked, or inline form (FAILED - 1)

Failures:

  1) Add new comment  add post via horizontal, stacked, or inline form
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit root_path
          EOFError:
            end of file reached
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:55:in `read_nonblock'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:55:in `read'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:46:in `gets'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:299:in `check'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:211:in `command'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:19:in `visit'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:48:in `visit'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
          # ./spec/features/comments_spec.rb:5:in `block (2 levels) in <top (required)>'
          # ./spec/rails_helper.rb:42:in `block (3 levels) in <top (required)>'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
          # ./spec/rails_helper.rb:41:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: Unable to find matching line from backtrace
          Capybara::Webkit::CrashError:
            The webkit_server process crashed!

              Broken pipe

            This is a bug in capybara-webkit. For help with this crash, please visit:

            https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:215:in `rescue in command'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:205:in `command'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/browser.rb:79:in `current_url'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:44:in `current_url'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara/session.rb:175:in `current_url'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:53:in `block in after_failed_example'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-2.4.4/lib/capybara.rb:277:in `using_session'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:52:in `after_failed_example'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/capybara-screenshot-1.0.11/lib/capybara-screenshot/rspec.rb:82:in `block (2 levels) in <top (required)>'
          # ./spec/rails_helper.rb:42:in `block (3 levels) in <top (required)>'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
          # /Users/justin/.rvm/gems/ruby-2.2.2@rails42/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
          # ./spec/rails_helper.rb:41:in `block (2 levels) in <top (required)>'

Finished in 2.49 seconds (files took 2.37 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/comments_spec.rb:4 # Add new comment  add post via horizontal, stacked, or inline form
```

**Comment by dylangrafmyre** [comment]
@justin808 This is an issue when using capybara-webkit. Everything works properly using selenium-webdriver. Rolling back to the to the gemfile.lock, capybara-webkit 1.5.1, from master branch to did not resolve the issue with the failing test.

**Comment by dylangrafmyre** [comment]
@justin808 Got it to work using Poltergeist and es5-shim-rails gem. Test pass and build succeeded on Codeship. This way we do not have to use selenium-webdriver and Firefox.
